# Generated by Django 3.2 on 2023-01-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionList',
        ),
    ]
